services:
  php:
    image: phpstorm/php-apache:8.2-xdebug3.2
    volumes:
      - .:/var/www
  web:
    build: .
    ports:
      - "8080:80"
    links:
      - db
    volumes:
      - ./:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: forum
    volumes:
      - forum_data:/var/lib/mysql
volumes:
  forum_data: